apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"integration","app.kubernetes.io/component":"integration","app.kubernetes.io/instance":"integration","app.kubernetes.io/name":"integration","app.kubernetes.io/part-of":"integration-app"},"name":"integration","namespace":"int-frontend"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"integration"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"integration","deployment":"integration","sidecar.istio.io/inject":"true"}},"spec":{"containers":[{"image":"registry.dev.sbiepay.sbi:8443/ubi9/integration:081020251","imagePullPolicy":"IfNotPresent","name":"integration","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2025-10-08T15:03:32Z"
  generation: 17
  labels:
    app: integration
    app.kubernetes.io/component: integration
    app.kubernetes.io/instance: integration
    app.kubernetes.io/name: integration
    app.kubernetes.io/part-of: integration-app
  name: integration
  namespace: int-frontend
  resourceVersion: "483370571"
  uid: 9487a3d4-dcc5-46c9-89b8-f4eda9869ef2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: integration
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-31T10:36:25Z"
      creationTimestamp: null
      labels:
        app: integration
        deployment: integration
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: registry.dev.sbiepay.sbi:8443/ubi9/merchantintegration:integration-3110251
        imagePullPolicy: IfNotPresent
        name: integration
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-27T10:58:24Z"
    lastUpdateTime: "2025-10-27T10:58:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-08T15:03:32Z"
    lastUpdateTime: "2025-10-31T10:36:28Z"
    message: ReplicaSet "integration-6cd468f898" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
